version: '3'
services:
  app1:
    build: ./app-load-balancing-1
    ports:
      - "8081:8081"
    environment:
      Bot_Token: 1990206478:AAEGm4ZhQFMakHOn6iqHWVrebPekFCR6Vvs
  app2:
    build: ./app-load-balancing-2
    ports:
      - "8082:8082"
    environment:
      Bot_Token: 1990206478:AAEGm4ZhQFMakHOn6iqHWVrebPekFCR6Vvs
  nginx:
    build: ./nginx
    ports:
      - "8888:80"
    depends_on:
      - app1
      - app2